"""
downstream/run_linearization_task.py
======================================
End-to-end orchestrator for Typology-Conditioned Dependency Linearization.

This is the THIRD downstream task, extending the arc-direction prediction
task (run_direction_task.py) to the sentence level.

Architecture difference from run_direction_task.py
---------------------------------------------------
run_direction_task:   corpus-level  →  predict mean p(dep<head) per language
run_linearization:    sentence-level →  predict token order for a specific sentence

The two tasks share the same MLPPredictor architecture and representations.
The key difference is evaluation: instead of comparing predicted p against
observed p across all treebank arcs, we evaluate the predicted total linear
ordering of each sentence against its gold order in the treebank.

Phases
------
1. Train direction predictors (calls run_direction_task.py infrastructure)
   OR load existing predictors from a previous run_direction_task run.

2. Self-linearization evaluation
   For each target language: apply its own embedding to reorder test sentences.
   Baseline: uses the gold direction profile as oracle (upper bound).
   Metric: Kendall's tau — how close is the predicted order to gold?

3. Value-holdout linearization (critical test)
   For held-out word-order languages (VOS/OVS/no-dominant-order):
   Apply the MLP predictor (trained WITHOUT these value types) to reorder
   test sentences in those languages.
   This directly tests cold-value generalization:
     - Repr C: zero bit for held-out value → predicts training mean → likely wrong
     - Repr B: expected embedding positioned in value space → can interpolate

4. Relinearized source treebanks (for downstream parsing)
   For each (source, target) language pair:
   Reorder source training sentences to look like target language.
   Write relinearized .conllu files for parser training.

5. Results compilation and comparison table.

Usage
-----
Full run:
    python downstream/run_linearization_task.py \\
        --manifest downstream_results/ud_data/manifest.json \\
        --profiles downstream_direction/arc_directions/direction_profiles.csv \\
        --splits_file downstream_direction/splits/splits.json \\
        --repr_base downstream_direction/representations \\
        --ckpt_wals checkpoints/wals_learned_s42 \\
        --ckpt_grambank checkpoints/grambank_learned_s42 \\
        --out_dir downstream_linearization \\
        --device cuda \\
        --train_first          # re-train direction predictors

Skip training (use previously saved results):
    python downstream/run_linearization_task.py \\
        --manifest ... --profiles ... --splits_file ... \\
        --repr_base downstream_direction/representations \\
        --out_dir downstream_linearization \\
        --skip_train

Smoke test:
    python downstream/run_linearization_task.py \\
        --manifest /tmp/ud_smoke/manifest.json \\
        --out_dir /tmp/lin_smoke \\
        --smoke
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
import pandas as pd

_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))


def parse_args(argv=None):
    p = argparse.ArgumentParser(
        description="TCDL: Typology-Conditioned Dependency Linearization pipeline",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    # Data
    p.add_argument("--manifest",     required=True)
    p.add_argument("--profiles",     default=None,
                   help="direction_profiles.csv (generated by arc_directions.py). "
                        "If absent, will run Phase 1 of arc extraction.")
    p.add_argument("--splits_file",  default=None,
                   help="splits.json (generated by value_splits.py). "
                        "If absent, will run split generation.")

    # Representations
    p.add_argument("--repr_base",    default=None,
                   help="Base dir for saved representations "
                        "(default: out_dir/representations)")
    p.add_argument("--ckpt_wals",    default="checkpoints/wals_learned_s42")
    p.add_argument("--ckpt_grambank",default="checkpoints/grambank_learned_s42")
    p.add_argument("--reprs",        default="A,B,C,B_masked30,B_masked50")
    p.add_argument("--seeds",        default="42")

    # Model training
    p.add_argument("--train_first",  action="store_true",
                   help="Train direction predictors before linearizing. "
                        "Required if no saved predictors exist.")
    p.add_argument("--n_epochs",     type=int, default=100)
    p.add_argument("--patience",     type=int, default=15)
    p.add_argument("--device",       default="cpu", choices=["cpu","cuda","mps"])

    # Evaluation
    p.add_argument("--max_sentences", type=int, default=500,
                   help="Cap test sentences per language (0=all)")
    p.add_argument("--build_synthetic_treebanks", action="store_true",
                   help="Build relinearized source treebanks for parser training")

    # Control
    p.add_argument("--out_dir",      required=True)
    p.add_argument("--skip_train",   action="store_true")
    p.add_argument("--smoke",        action="store_true",
                   help="Minimal run: 3 languages, 3 epochs")
    p.add_argument("--overwrite",    action="store_true")
    return p.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    os.chdir(_REPO_ROOT)
    os.makedirs(args.out_dir, exist_ok=True)

    if args.smoke:
        args.n_epochs = 3
        args.patience = 2
        args.reprs    = "A,B"
        args.device   = "cpu"
        args.max_sentences = 100
        print("SMOKE TEST: 3 epochs, reprs=A,B, CPU, 100 sentences")

    seeds = [int(s) for s in args.seeds.split(",")]
    reprs = [r.strip() for r in args.reprs.split(",")]

    dirs = {
        "arc":    os.path.join(args.out_dir, "arc_directions"),
        "splits": os.path.join(args.out_dir, "splits"),
        "repr":   args.repr_base or os.path.join(args.out_dir, "representations"),
        "models": os.path.join(args.out_dir, "models"),
        "linear": os.path.join(args.out_dir, "linearization"),
        "synth":  os.path.join(args.out_dir, "synthetic_treebanks"),
        "results":os.path.join(args.out_dir, "results"),
    }
    for d in dirs.values():
        os.makedirs(d, exist_ok=True)

    with open(args.manifest) as f:
        manifest = json.load(f)

    # ── Phase 0: Arc extraction if needed ────────────────────────────────
    profiles_path = args.profiles or os.path.join(dirs["arc"], "direction_profiles.csv")
    if not os.path.exists(profiles_path):
        print("\n" + "="*60)
        print("PHASE 0: Extracting arc-direction profiles")
        print("="*60)
        from downstream.arc_directions import extract_all_profiles
        profiles_df = extract_all_profiles(manifest, dirs["arc"])
    else:
        profiles_df = pd.read_csv(profiles_path, index_col=0)
        print(f"Loaded profiles: {profiles_df.shape}")

    counts_path = os.path.join(os.path.dirname(profiles_path), "direction_counts.csv")
    counts_df = pd.read_csv(counts_path, index_col=0) \
                if os.path.exists(counts_path) \
                else pd.DataFrame(1.0, index=profiles_df.index, columns=profiles_df.columns)

    # ── Phase 0b: Split generation if needed ─────────────────────────────
    splits_path = args.splits_file or os.path.join(dirs["splits"], "splits.json")
    if not os.path.exists(splits_path):
        print("\nGenerating evaluation splits...")
        from downstream.value_splits import build_all_splits
        splits = build_all_splits(profiles_df, args.ckpt_wals, dirs["splits"])
    else:
        with open(splits_path) as f:
            splits = json.load(f)
        print(f"Loaded splits: {list(splits.keys())}")

    # ── Phase 1: Extract representations ─────────────────────────────────
    print("\n" + "="*60)
    print("PHASE 1: Loading / extracting representations")
    print("="*60)

    from downstream.representations import (
        load_checkpoint, compute_repr_A, compute_repr_B,
        compute_repr_C, compute_repr_B_masked,
    )

    glottocodes = profiles_df.index.tolist()
    repr_store: Dict = {}

    for seed in seeds:
        for db, ckpt_path in [("wals", args.ckpt_wals),
                               ("grambank", args.ckpt_grambank)]:
            ckpt_dir = ckpt_path.replace("s42", f"s{seed}")
            if not os.path.exists(ckpt_dir):
                continue
            repr_dir = os.path.join(dirs["repr"], f"{db}_s{seed}")
            os.makedirs(repr_dir, exist_ok=True)
            ckpt = load_checkpoint(ckpt_dir)
            target_glots = [g for g in glottocodes if g in ckpt["lang2id"]]

            for repr_name in reprs:
                key = f"{db}_s{seed}_{repr_name}"
                npy = os.path.join(repr_dir, f"repr_{repr_name}.npy")
                lpath = os.path.join(repr_dir, f"repr_{repr_name}_langs.json")

                if os.path.exists(npy) and not args.overwrite:
                    mat = np.load(npy)
                    with open(lpath) as f: langs = json.load(f)
                else:
                    if repr_name == "A":
                        mat, langs = compute_repr_A(ckpt, target_glots)
                    elif repr_name == "B":
                        mat, langs = compute_repr_B(ckpt, target_glots)
                    elif repr_name == "C":
                        mat, langs = compute_repr_C(ckpt, target_glots)
                    elif repr_name.startswith("B_masked"):
                        frac = int(repr_name[8:]) / 100
                        mat, _, langs = compute_repr_B_masked(ckpt, target_glots, frac)
                    else:
                        continue
                    np.save(npy, mat)
                    with open(lpath, "w") as f: json.dump(langs, f)

                repr_store[key] = {"matrix": mat, "langs": langs}
                print(f"  {key}: {mat.shape}")

    # ── Phase 2: Train direction predictors ───────────────────────────────
    predictors: Dict = {}

    if args.train_first and not args.skip_train:
        print("\n" + "="*60)
        print("PHASE 2: Training direction predictors")
        print("="*60)

        from downstream.direction_predictor import (
            MLPPredictor, evaluate_predictions,
        )

        # Use Split A (random holdout) for training predictors
        split_A = splits.get("A_random", {})
        train_glots = split_A.get("train", glottocodes)
        dev_glots   = split_A.get("test", [])[:5]

        for repr_key, repr_data in repr_store.items():
            mat   = repr_data["matrix"]
            langs = repr_data["langs"]
            lang_dim = mat.shape[1]
            glot2row = {g: i for i, g in enumerate(langs)}

            train_g = [g for g in train_glots if g in glot2row and g in profiles_df.index]
            dev_g   = [g for g in dev_glots   if g in glot2row and g in profiles_df.index]

            if len(train_g) < 3:
                continue

            train_mat = np.array([mat[glot2row[g]] for g in train_g])
            dev_mat   = np.array([mat[glot2row[g]] for g in dev_g]) if dev_g else None

            pred = MLPPredictor(
                lang_dim=lang_dim,
                n_epochs=args.n_epochs,
                patience=args.patience,
                device=args.device,
                repr_name=repr_key,
            )
            print(f"\n  Training {repr_key} on {len(train_g)} languages...")
            pred.fit(
                train_glots=train_g,
                lang_reprs=train_mat,
                profiles=profiles_df,
                counts=counts_df,
                dev_glots=dev_g,
                verbose=True,
            )
            predictors[repr_key] = pred

            # Save model
            model_path = os.path.join(dirs["models"], f"{repr_key}_mlp.pt")
            if pred.model is not None:
                import torch
                torch.save(pred.model.state_dict(), model_path)
                print(f"  Saved: {model_path}")
    else:
        # Try to load saved predictors
        from downstream.direction_predictor import MLPPredictor
        for repr_key, repr_data in repr_store.items():
            model_path = os.path.join(dirs["models"], f"{repr_key}_mlp.pt")
            if os.path.exists(model_path):
                import torch
                lang_dim = repr_data["matrix"].shape[1]
                pred = MLPPredictor(lang_dim=lang_dim, device=args.device)
                # Build model architecture first
                from downstream.direction_predictor import _build_mlp_model
                n_rels = len(pred.rel2id)
                n_upos = len(pred.upos2id)
                pred.model = _build_mlp_model(lang_dim, n_rels, n_upos).to(args.device)
                pred.model.load_state_dict(
                    torch.load(model_path, map_location=args.device, weights_only=True))
                pred.model.eval()
                predictors[repr_key] = pred
                print(f"  Loaded predictor: {repr_key}")
            else:
                print(f"  No saved predictor for {repr_key} — will use oracle/baseline only")

    # ── Phase 3: Linearization evaluation ────────────────────────────────
    print("\n" + "="*60)
    print("PHASE 3: Linearization evaluation")
    print("="*60)

    from downstream.linearization_eval import run_full_evaluation
    df = run_full_evaluation(
        manifest=manifest,
        profiles_df=profiles_df,
        splits=splits,
        repr_store=repr_store,
        predictors=predictors,
        out_dir=dirs["linear"],
        device=args.device,
        max_sentences=args.max_sentences or 500,
    )

    # ── Phase 4: Build synthetic treebanks ───────────────────────────────
    if args.build_synthetic_treebanks:
        print("\n" + "="*60)
        print("PHASE 4: Building relinearized source treebanks")
        print("="*60)

        from downstream.arc_directions import parse_conllu_arcs
        from downstream.linearizer import Linearizer, rewrite_conllu

        # Build treebanks for each value-holdout target using each repr
        for split_name, split_data in splits.items():
            if "value" not in split_name:
                continue
            test_glots = split_data.get("test", [])

            # For each test language, relinearize the best available source
            for tgt_glot in test_glots:
                if tgt_glot not in manifest or "train" not in manifest.get(tgt_glot, {}):
                    continue
                for repr_key, repr_data in repr_store.items():
                    if repr_key not in predictors:
                        continue
                    mat, langs = repr_data["matrix"], repr_data["langs"]
                    glot2row = {g: i for i, g in enumerate(langs)}
                    if tgt_glot not in glot2row:
                        continue
                    lang_repr = mat[glot2row[tgt_glot]]
                    predictor = predictors[repr_key]

                    # Use English as source (largest treebank)
                    src_glot = "stan1293"
                    if src_glot not in manifest or "train" not in manifest[src_glot]:
                        continue

                    with open(manifest[src_glot]["train"], encoding="utf-8") as f:
                        src_text = f.read()
                    from downstream.arc_directions import parse_conllu_arcs
                    sents = parse_conllu_arcs(src_text)

                    lin = Linearizer(predictor, lang_repr, device=args.device)
                    orders = lin.linearize_corpus(sents)

                    out_path = os.path.join(
                        dirs["synth"],
                        f"{src_glot}_relinearized_as_{tgt_glot}_{repr_key}.conllu")
                    rewrite_conllu(src_text, orders, out_path)
                    print(f"  {src_glot}→{tgt_glot} ({repr_key}): {len(sents)} sentences")

    # ── Phase 5: Summary ─────────────────────────────────────────────────
    print("\n" + "="*60)
    print("PHASE 5: Results Summary")
    print("="*60)

    results_path = os.path.join(dirs["results"], "linearization_summary.csv")
    if not df.empty:
        df.to_csv(results_path, index=False)

        # Key comparison: B vs C on value-holdout
        val_df = df[df["condition"].str.contains("value", na=False)]
        if not val_df.empty:
            print("\n--- KEY RESULT: Value-holdout linearization ---")
            print(f"{'Repr':<35} {'Target':>10} {'Tau':>8} {'PairAcc':>9} {'ArcAcc':>8}")
            print("-"*75)
            for _, r in val_df.sort_values("kendall_tau", ascending=False).iterrows():
                print(f"  {r['repr']:<33} {r['target_glot']:>10} "
                      f"{r['kendall_tau']:>8.4f} {r['pair_accuracy']:>9.4f} "
                      f"{r.get('arc_accuracy', float('nan')):>8.4f}")

        # Self-linearization summary
        self_df = df[df["condition"] == "self"]
        if not self_df.empty:
            print("\n--- SELF-linearization: mean Kendall tau ---")
            summary = (self_df.groupby("repr")["kendall_tau"]
                              .agg(["mean", "std"])
                              .sort_values("mean", ascending=False))
            print(summary.to_string(float_format="{:.4f}".format))

    print(f"\n{'='*60}")
    print("LINEARIZATION TASK COMPLETE")
    print(f"Results: {dirs['results']}")
    print(f"\nTo run the downstream parser, use the synthetic treebanks in:")
    print(f"  {dirs['synth']}")
    print("and train with downstream/tagger.py (POS) or a biaffine parser.")


if __name__ == "__main__":
    main()
